### ISSUE TITLE
申请友链

### ISSUE THREAD

**Issue by rmolives** [shirohako/helm#1]
https://psychol.cn
PsycholCN致力于普及心理健康相关知识，并改善特定人群的歧视及误解等问题。
https://psychol.cn/w/logo.png

**Comment by shirohako** [comment]
> https://psychol.cn PsycholCN致力于普及心理健康相关知识，并改善特定人群的歧视及误解等问题。 https://psychol.cn/w/logo.png

感谢您的申请。已经添加`PsycholCN`的链接

如需要本站信息，可以复制下面内容
> title: Atelier Abyss
> link: https://abyss.moe or https://blog.abyss.moe
> img/icon: https://i.psray.net/i/2024/04/21/6624dd2e9a5c4.jpg

**Comment by shirohako** [comment]
暂时移除了`PsycholCN`您的友联。

因为以下原因：移除单向链接
